# Integration All plugin files - combines all development tools
integration-all/integration-all.desktop usr/share/deepin/dde-file-manager/oem-menuextensions
integration-all/integration.svg usr/share/dde-file-manager-extramenu-plugins

# build-deb
build-deb/quick-build-deb.sh usr/bin
build-deb/deb-package-icon.svg usr/share/dde-file-manager-extramenu-plugins

# gitk
cat-gitk/gitk-launcher.sh usr/bin
cat-gitk/gitk-icon.svg usr/share/dde-file-manager-extramenu-plugins

# deepin-project-downloader
deepin-project-downloader/dde-project-downloader.sh usr/bin
deepin-project-downloader/deepin-project-downloader.svg usr/share/dde-file-manager-extramenu-plugins
deepin-project-downloader/deepin-project-downloader-backen.py usr/share/dde-file-manager-extramenu-plugins

# dde-dconfig-editor
dde-dconfig-editor/dde-dconfig-editor.svg usr/share/dde-file-manager-extramenu-plugins

# d-feet
d-feet/d-feet.svg usr/share/dde-file-manager-extramenu-plugins